### ISSUE TITLE
VISIT_OCCURRENCE field mis-labeled

### ISSUE THREAD

**Issue by markmayer** [UNMCCC/CRIIS_Source_Extracts_for_OMOP#82] opened 2022-02-15 20:18 UTC
Please rename REFERRED_TO_CONCEPT_ID to DISCHARGE_TO_CONCEPT_ID

**Comment by lvarnedoe** [comment] 2022-02-28 21:26
closing - duplicate of other requests - addressed in #83

**Closed by lvarnedoe** 2022-02-28 21:26 UTC
Labels: duplicate
